CREATE DATABASE ClinicManagementDB;
GO

USE ClinicManagementDB;
GO

CREATE TABLE Countries (
CountryID TINYINT PRIMARY KEY IDENTITY(1,1),
CountryName NVARCHAR(60) NOT NULL UNIQUE
)

CREATE TABLE Departments (
DepartmentID SMALLINT PRIMARY KEY IDENTITY(1,1),
DepartmentName NVARCHAR(120) NOT NULL UNIQUE,
Location NVARCHAR(100) NOT NULL
)

CREATE TABLE People (
PersonID INT PRIMARY KEY IDENTITY(1,1),
FirstName NVARCHAR(22) NOT NULL,
SecondName NVARCHAR(22) NOT NULL,
ThirdName NVARCHAR(22) NULL,
LastName NVARCHAR(22) NOT NULL,
NationalIdentificationNumber NVARCHAR(10) NOT NULL UNIQUE,
BirthDate DATE NOT NULL,
Gender BIT NOT NULL,
Address NVARCHAR(250) NULL,
Phone NVARCHAR(12) NOT NULL,
Email NVARCHAR(255) NOT NULL,
CountryID TINYINT NOT NULL FOREIGN KEY REFERENCES Countries(CountryID),
)

CREATE TABLE Users (
UserID INT PRIMARY KEY IDENTITY(1,1),
PersonID INT FOREIGN KEY REFERENCES People(PersonID) NOT NULL,
Username NVARCHAR(22) NOT NULL,
Password NVARCHAR(64) NOT NULL,
IsActive BIT NOT NULL,
CreatedAt DATETIME NOT NULL,
UpdatedAt DATETIME NULL
)

CREATE TABLE Doctors (
DoctorID INT PRIMARY KEY IDENTITY(1,1),
PersonID INT FOREIGN KEY REFERENCES People(PersonID),
LicenseNumber NVARCHAR(6) NOT NULL,
Specialization NVARCHAR(60) NOT NULL,
YearsOfExperience TINYINT NOT NULL,
DepartmentID SMALLINT NOT NULL FOREIGN KEY REFERENCES Departments(DepartmentID),
HireDate DATE NOT NULL,
EndDate DATE NULL,
Status TINYINT NOT NULL, -- Status: 1 = Active, 2 = On Leave, 3 = Left Job, 4 = Retired)
CreatedAt DATETIME NOT NULL,
UpdatedAt DATETIME NULL,
CreatedByUserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL
)


CREATE TABLE Patients(
PatientID INT PRIMARY KEY IDENTITY(1,1),
PersonID INT FOREIGN KEY REFERENCES People(PersonID),
BloodType NVARCHAR(3) NULL,
Allergies NVARCHAR(240) NULL,
MedicalHistory NVARCHAR(360) NULL,
RegistrationDate DATE NOT NULL,
CreatedAt DATETIME NOT NULL,
UpdatedAt DATETIME NULL,
CreatedByUserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL
)

CREATE TABLE Appointments (
AppointmentID INT PRIMARY KEY IDENTITY(1,1),
PatientID INT FOREIGN KEY REFERENCES Patients(PatientID) NOT NULL,
DoctorID INT FOREIGN KEY REFERENCES Doctors(DoctorID) NOT NULL,
AppointmentDate DATE NOT NULL,
Status TINYINT NOT NULL, -- 1 = Scheduled, 2 = Completed, 3 = Cancelled, 4 = Rescheduled, 5 = No Show
CreatedAt DATETIME NOT NULL,
UpdatedAt DATETIME NULL,
CreatedByUserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL
)

CREATE TABLE MedicalRecords(
MedicalRecordID INT PRIMARY KEY IDENTITY(1,1),
AppointmentID INT FOREIGN KEY REFERENCES Appointments(AppointmentID) NOT NULL,
Diagnosis NVARCHAR(128) NULL,
Medications NVARCHAR(128) NULL,
Notes NVARCHAR(128) NULL,
CreatedAt DATETIME NOT NULL
)



